# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_name',
            new_name='img_name',
        ),
    ]
