# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20170922_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(null=True, upload_to='photoimg'),
        ),
    ]
