# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20170925_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(default=0, upload_to='photoimg'),
            preserve_default=False,
        ),
    ]
